apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pypicloud.fullname" . }}
  labels:
    app: {{ include "pypicloud.name" . }}
    chart: {{ include "pypicloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  # All files from the config directory, will be mounted in /etc/config through this configmap
{{ (.Files.Glob "config/*").AsConfig | indent 2 }}